@startuml
'https://plantuml.com/class-diagram

class Article
class ArticleParam
class ArticleTag
class ArticleBody
class CategoryVo
class ArticleBodyParam
class TagVo
ArticleBodyParam --> ArticleParam
CategoryVo --> ArticleParam
TagVo --> ArticleParam




@enduml